### ISSUE TITLE
npy file not found error

### ISSUE THREAD

**Issue by sshen82** [ma-compbio/Higashi#1]
Hi, I am trying to use the Process.py file, but during "generating node attributes", it shows error that "chr1_cell_adj.npy" file not found. I guess this file is generated during the process of running the code, because I didn't see it in README. Do you know what might cause the error?

Below is the full message:

Code: python Process.py -c /p/keles/schic/volumeA/Ren2019/higashi_files/data.json

scale_factor 1
cpu_num 56
max bin 100000.0
min bin 1
generating node attributes
Traceback (most recent call last):
  File "Process.py", line 403, in generate_feats
    temp = np.load(os.path.join(temp_dir, "%s_cell_%s.npy" % (c, ext_str)), allow_pickle=True).item()
  File "/u/s/s/sshen82/miniconda3/envs/higashi/lib/python3.7/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/p/keles/schic/volumeA/Ren2019/higashi_files/temp/chr1_cell_adj.npy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Process.py", line 533, in <module>
    generate_feats(optional_smooth_flag)
  File "Process.py", line 405, in generate_feats
    temp = np.load(os.path.join(temp_dir, "%s_cell_%s.npy" % (c, ext_str)), allow_pickle=True)
  File "/u/s/s/sshen82/miniconda3/envs/higashi/lib/python3.7/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/p/keles/schic/volumeA/Ren2019/higashi_files/temp/chr1_cell_adj.npy'

**Comment by sshen82** [comment]
I looked into the Process.py code, and "generate_feat_one" function isn't used. It might be the reason of the error.

**Comment by ruochiz** [comment]
Hi,

Thanks for your interest in our method. I was tuning/running Higashi as well as cleaning code these days. I might have pushed some unfinished updates to the repo. I'll do a quick check and update the repo tomorrow.
