### ISSUE TITLE
batch information not loaded?

### ISSUE THREAD

**Issue by sshen82** [ma-compbio/Higashi#13]
Hi Ruochi,
I tried the new version of Higashi on the classical Lee et al. 2019 data, but find that the result still doesn't include the batch information. The zip file contains my json file and the pickle file. I think the batch is included clearly. Do you know what might be the error?

![image](https://user-images.githubusercontent.com/29969832/143783984-f61c11d2-2b00-416b-93c8-0acc4bd2a413.png)

[DataInfo.zip](https://github.com/ma-compbio/Higashi/files/7614270/DataInfo.zip)

Yours sincerely,
Siqi Shen

**Comment by ruochiz** [comment]
Hi Siqi,

The JSON file looks good to me. I attach the JSON file I use when running this dataset for your reference. I'm now running the latest Higashi on the PFC dataset (with the JSON file I attached). Will send the results once I have them.


[config_m3c_500Kb.JSON.zip](https://github.com/ma-compbio/Higashi/files/7614293/config_m3c_500Kb.JSON.zip)
