### ISSUE TITLE
Integration with deep sequenced bulk Hi-C

### ISSUE THREAD

**Issue by yuhao-blsa** [ma-compbio/Higashi#14]
Hi ruochiz,
I just test Higashi on scHi-C data with low coverage per cell (~10,000 cis reads per cell), and found the cell diversity is low. Is it possible to combine scHi-C data with deep sequenced bulk Hi-C data to improve the result? BTW, adding bulk data as a single node seems to make no difference.
Thanks!

**Comment by ruochiz** [comment]
Hi John,

Yes. We are working on one function to include the bulk Hi-C as features for the genomic bin nodes. I'll update this thread once that function is pushed to the repo. We found that it can improve the imputation results. 

Just to clarify, what do you mean by "low cell diversity"? Is it the imputed contact maps or embeddings? And what resolution are you trying to apply Higashi on?

**Comment by yuhao-blsa** [comment]
The function is totally different from `bulk_path` in the configure file, right？It sounds exciting to learn bin-bin relationship from bulk Hi-C. 
I meant the cell embeddings, as most cells gathered together rather than divided into several groups. And the resolution is 1Mb. I also found the cis reads per cell vary dramatically, and may interfere with clustering.

**Comment by ruochiz** [comment]
1. The function would be different, but we'll probably reuse the `bulk_path` and add another option. (Something like `use_bulk_bin_feats`)
2. If it's that the cell embeddings are clustered together, I don't think the above option would help with the cell embeddings. 
3. Based on your description, I think it's similar to the 4DN sci-Hi-C dataset (Kim et al.) we worked on before. The following is the statistics for it. (Note that the definition of contacts per cell is different from common contacts. In the table the # of contacts are # of interactions between different 1Mb bins. ) Higashi can have good performance on these two dataset. 

<img width="361" alt="CleanShot 2021-12-03 at 14 25 27@2x" src="https://user-images.githubusercontent.com/8788626/144661259-ee8ccf91-3720-4c0c-8332-b8a243a73b40.png">

**Comment by yuhao-blsa** [comment]
Thanks for your kind reply!
Yes, you're right , the contacts per cell is similar to the 4DN sci-Hi-C dataset and seems acceptable. May be I should take experimental factor into account.
Datasets             | Mean Min Median Max   |
The data we use | 7.0k   0.1k    6.2k   27.1k  |
