### ISSUE TITLE
conda install not working

### ISSUE THREAD

**Issue by seburgess** [ma-compbio/Higashi#16]
attempting to install on MacBook Pro with OS 10.15.7 I get the error:

PackagesNotFoundError: The following packages are not available from current channels:

  - higashi

Current channels:

  - https://conda.anaconda.org/ruochiz/osx-64
  - https://conda.anaconda.org/ruochiz/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

**Comment by ruochiz** [comment]
Thank you for your feedback.

This error occurs because I did not compile the package under the OSX platform. Current conda installation only supports the linux platform. The support for OSX platform will be included in the next release version.

**Comment by seburgess** [comment]
Thanks!
