### ISSUE TITLE
I cannot install Higashi through conda. My computer doesn't have gpu.

### ISSUE THREAD

**Issue by EddieLv** [ma-compbio/Higashi#17]
My system is linux without gpu,
1. create a conda env named higashi
2. conda install python==3.9
3. conda install pytorch torchvision torchaudio cpuonly -c pytorch
4. conda install -c ruochiz higashi
Here comes the error:
![3c0ffdc6cc5b09a15795d2fffcfe592](https://user-images.githubusercontent.com/61786787/164971088-8bf7f7b7-8bf2-4a75-a56c-f903cba02770.png)

**Comment by ruochiz** [comment]
Thank you for your feedback. I will look into it, it does seem that the conda build only works for some of the machines (2 out of 3 machines that I tested on can install the package, the other one failed without any detailed error information). Meanwhile, could you try if you can install the package through the git clone + python setup.py way? Thanks.

**Comment by EddieLv** [comment]
Thanks for your reply. I successfully installed the Higahi through the git clone way.
1.create a conda env named higashi
2.conda install python==3.9
3.conda install pytorch torchvision torchaudio cpuonly -c pytorch
4.python setup.py install
And I can also run Higashi in jupyter notebook.

**Comment by ruochiz** [comment]
Thank you for testing! I will try to make the conda install work and more compatible.
