### ISSUE TITLE
About parameter k in JSON file

### ISSUE THREAD

**Issue by sshen82** [ma-compbio/Higashi#2]
Hi, sorry I have a question again. In your description, you said that "Train Higashi with cell-dependent GNN, but with k=k in the configuration JSON When {START_STEP} is 1, the program would execute step 1,2,3 sequentially." However, I didn't see k in the tutorial of json file.  What do I need to input if I only want the first step? 

By the way, I find that when running the code, it will run for at least two times, one with epoch of 20, and one with epoch of 120 (maybe there are others after this, but I didn't continue it), is this step 1, 2, and 3?

EDIT:
After reading your code, I think the second question is solved. However, the first one is still unclear. There is another question that can I change the epoch? Since it is not changing much on my dataset. Or on your experience, is this only happening on my own dataset, or is this just that accuracy won't change much among different epochs.

**Comment by ruochiz** [comment]
Hi,

the $k$ is actually the neighbor_num parameter in the JSON file. 

The first 20 epochs are just using cell associated features such as total read count per cell, batch id etc to regress out the potential bias, while the 120 epochs are running for the actual step 1. 

You can change the number of epochs for sure. But one thing I notice is that although the auc/aupr values are not changing much, the embeddings can still change a lot. To check that, you might notice there is an "update rate" printed out per epoch indicating the min/max change of the embeddings (normalized by the l2 norm). If you see those numbers are really small, then the model actually converges. The test results showed that 80~90 epochs are sufficient for the datasets we studied. 120 is just to be safe.

If you have a follow up question, I would be happy to discuss through the email. ruochiz@andrew.cmu.edu.
