### ISSUE TITLE
Conda install doesn't work as expected

### ISSUE THREAD

**Issue by Dududu233** [ma-compbio/Higashi#20]
I tried to install higashi with 
'conda install -c ruochiz higashi',
 but get an error feature:/linux-64::__glibc==2.27=0 feature:|@/linux-64::__glibc==2.27=0
 
![image](https://user-images.githubusercontent.com/86656612/178181745-13f74461-665b-45e0-ab59-54208ccd79ad.png)

I don't know how to solve this problem. Or which version of glibc should I use。

**Comment by ruochiz** [comment]
Hi,

Thanks for your interest. I'm still working on this issue. Somehow the conda compilation only works for some environment while failing to solve on others (I can reproduce this error on some of the machines). I'm still working on that. Meanwhile, you could try to install it with the python setup.py install method. Thanks
