### ISSUE TITLE
Moudle import error

### ISSUE THREAD

**Issue by Dududu233** [ma-compbio/Higashi#21]
Sorry to bother you again.
I 've seccessfully installed higashi. When I try to run tutorials, it produces the error shown in the figure. 
It seems that there is something wrong in process.py, how can I fix it.
![image](https://user-images.githubusercontent.com/86656612/178645040-1477944b-e87e-460b-a605-5d9ba185da16.png)
![image](https://user-images.githubusercontent.com/86656612/178645069-1ce8c777-adfe-425b-9f89-aad65a8295f0.png)

**Comment by ruochiz** [comment]
Could you include lines below in your first figure? It seems that the error is triggered when trying to import scipy.signal module.

And could you also list your scipy version please, Thx.

**Comment by Dududu233** [comment]
I modified the code in process.py into this，the prolem solved.

![image](https://user-images.githubusercontent.com/86656612/178860915-7a416746-a04b-4279-9565-9747110710ed.png)
