### ISSUE TITLE
Higashi gets error during higashi_model.process_data()

### ISSUE THREAD

**Issue by AmyTanJ** [ma-compbio/Higashi#24]
Hi, ruochi! I'm trying to run Higashi at a low resolution, like 10kb.
It seems trigger a concurrent.futures.processBrokenFrocessPool error when creating matrices tasks.
I tried to run higashi from the CLI instead of the API, but the error persisted as below.

![image](https://user-images.githubusercontent.com/73063292/206639804-dfdb6f28-16c9-4295-abaf-22783d92ff5d.png)

Then, I tried to change "cpu" in configure from -1 to 1, and a new memory error occurs as below.
![a9647281ce87c48d3776f05fff42b1f](https://user-images.githubusercontent.com/73063292/206603147-91ee489a-57b7-4f02-844b-62065c313d79.png)

Do you know how to solve this problem when creating matrices tasks in higashi_model.process_data()?

Thanks!

**Comment by ruochiz** [comment]
That's the memory error. You would need to either run the code on a machine with larger memory size or switch to a lower resolution setting

**Comment by AmyTanJ** [comment]
您好，我是谭佳慧，您的邮件我已经收到，我会尽快回复，祝您万事如意，家庭幸福！
