### ISSUE TITLE
Generating a hdf5 file for storing the coassayed signals

### ISSUE THREAD

**Issue by nedashokraneh** [ma-compbio/Higashi#25]
Hi,

Do you have a script including the processing of Lee et al methylation data and how it is used to construct a co-assayed signal m_i per cell in the joint analysis? 

Thanks.

**Comment by ruochiz** [comment]
https://drive.google.com/drive/folders/1SuzqQ_9dliAmTb-fGprFnN3aZrfWS-Fg?usp=sharing

**Comment by ruochiz** [comment]
The data.txt corresponding to this file:
https://drive.google.com/drive/folders/1SuzqQ_9dliAmTb-fGprFnN3aZrfWS-Fg?usp=sharing
For reproducing purposes, the processed methylation data for this data:
https://drive.google.com/file/d/1xtN05kSgWP3yt_degcxWftb8xG85vMCR/view

If you want to process the signals, I recommend you check out the AllCools (https://github.com/lhqing/ALLCools) toolkit. It’s developed by the same group of people that generated the sn-m3c-seq dataset, and it's well documented.

In the manuscript, I use my own python script to process the data (resulting in the file shared above). I'll organize it a bit, add some comments, and upload the code later. Thx.

**Comment by nedashokraneh** [comment]
The tutorial is great. Thanks for sharing the data and your recommendation.
