### ISSUE TITLE
some question about json file

### ISSUE THREAD

**Issue by yangfeizZZ** [ma-compbio/Higashi#28]
Hello:
In your test ipynb file [see https://github.com/ma-compbio/Higashi/blob/main/tutorials/4DN_sci-Hi-C_Kim%20et%20al.ipynb], i have some question.
1, What is the label_info.pickle. I have data.txt but i don't know how to make the pickle file.
2, In the json,what is the data in the data_dir and temp_dir.

Thank you for your reply.

**Comment by ruochiz** [comment]
Hey, thanks for your interest.
1. For label_info.pickle, see wiki page for more details: https://github.com/ma-compbio/Higashi/wiki/Input-Files
2. within data_dir, there should be the data.txt and label_info.pickle. For temp_dir, Higashi would automatically creat some files like embeddings, imputations, etc. See more info here: https://github.com/ma-compbio/Higashi/wiki/Configure-the-parameters
