### ISSUE TITLE
NameError: name 'neg_num' is not defined

### ISSUE THREAD

**Issue by Queen0044** [ma-compbio/Higashi#29]
Hi Ruochi,

I followed the tutorial of Higashi on [Ramani et al.](https://github.com/ma-compbio/Higashi/blob/main/tutorials/Ramani%20et%20al.ipynb) and encountered the following error message: 
```
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/lib/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/user/Desktop/Higashi/Higashi/higashi/Higashi_wrapper.py", line 239, in one_thread_generate_neg
    if neg_num == 0:
NameError: name 'neg_num' is not defined
```
It seems the `neg_num` global variable is not defined anywhere else. How can I address this problem?

Thanks.

**Comment by ruochiz** [comment]
Hey, Thanks for your interest. yes, `neg_num` is a global variable that should be defined when calling the `prep_model()` function. Did you run it before running any training function? If so, I'll dig deeper to see what might trigger the bug.

**Comment by Queen0044** [comment]
Hi Ruochi,

Thank you for quick reply. I ran the following command following the tutorial, and got the error message after the last command. Where should I define neg_num? In the tutorial codes there is no such lines.


from higashi.Higashi_wrapper import *

config = "/Users/username/desktop/Higashi/simulation/config_ramani.JSON"

higashi_model = Higashi(config)



higashi_model.process_data()



higashi_model.prep_model()

higashi_model.train_for_embeddings()

Best;
Qing

From: ruochiz ***@***.***>
Reply-To: ma-compbio/Higashi ***@***.***>
Date: Sunday, March 19, 2023 at 1:51 PM
To: ma-compbio/Higashi ***@***.***>
Cc: Queen0044 ***@***.***>, Author ***@***.***>
Subject: Re: [ma-compbio/Higashi] NameError: name 'neg_num' is not defined (Issue #29)

Hey, Thanks for your interest. yes, neg_num is a global variable that should be defined when calling the prep_model() function. Did you run it before running any training function? If so, I'll dig deeper to see what might trigger the bug. —Reply


Hey, Thanks for your interest. yes, neg_num is a global variable that should be defined when calling the prep_model() function. Did you run it before running any training function? If so, I'll dig deeper to see what might trigger the bug.

**Comment by ruochiz** [comment]
neg_num should be defined within .prep_model() function automatically and be used as a global variable, you shouldn't need to define it yourself. I'll test it on my end to reproduce the error.

For more information, did you run the model in a jupyter notebook setting? python within shell? or python xx.py 

And how is higashi installed? (python setup.py install) or just clone the repo and run code at the root directory?

**Comment by Queen0044** [comment]
Hi Ruochi,

Please see my respond below. Thanks!

Best;
Qing

From: ruochiz ***@***.***>
Reply-To: ma-compbio/Higashi ***@***.***>
Date: Sunday, March 19, 2023 at 3:59 PM
To: ma-compbio/Higashi ***@***.***>
Cc: Queen0044 ***@***.***>, Author ***@***.***>
Subject: Re: [ma-compbio/Higashi] NameError: name 'neg_num' is not defined (Issue #29)

neg_num should be defined within .prep_model() function automatically and be used as a global variable, you shouldn't need to define it yourself. I'll test it on my end to reproduce the error. For more information, did you run the model in


neg_num should be defined within .prep_model() function automatically and be used as a global variable, you shouldn't need to define it yourself. I'll test it on my end to reproduce the error.

For more information, did you run the model in a jupyter notebook setting? python within shell? or python xx.py

I ran it in Python 3.9.13. on my Mac within shell.

And how is higashi installed? (python setup.py install) or just clone the repo and run code at the root directory?

I used the following lines to install:
git clone https://github.com/ma-compbio/Higashi/
cd Higashi
python setup.py install

**Comment by ruochiz** [comment]
Hey, somehow I cannot reproduce this error on my end. I create a new environment, clean installed Higashi, run it with python shell. Attached is the log for that.

[higashi_log.txt](https://github.com/ma-compbio/Higashi/files/11013208/higashi_log.txt)

**Comment by ruochiz** [comment]
Could you perhaps try it in a notebook setting. And attach the notebook after it encounters the error here, so I can gather more info of what's happening. This could be a system issue, or platform issue. If it's specific to MacOS, I can try to find a fix in the next release version.

**Comment by Queen0044** [comment]
[higashi_test.ipynb.zip](https://github.com/ma-compbio/Higashi/files/11046535/higashi_test.ipynb.zip)
Please find the attached notebook file. From the log after running `prep_model()`, it seems this step did not finish execution. This may be the reason that `neg_num` is never defined.

**Comment by ruochiz** [comment]
```
		# Dependes on the sparsity, change the number of negative samples
		if sparsity > 0.3:
			neg_num = 1
		elif sparsity > 0.2:
			neg_num = 2
		elif sparsity > 0.15:
			neg_num = 3
		elif sparsity > 0.1:
			neg_num = 4
		else:
			neg_num = 5
		
		self.batch_size *= (1 + neg_num)
		print("Node type num", self.num, num_list)
		start_end_dict = np.concatenate([np.zeros((1, 2)), start_end_dict], axis=0).astype('int')
		
		self.cell_feats = np.sum(self.cell_feats, axis=-1, keepdims=True)
		self.cell_feats1 = torch.from_numpy(self.cell_feats1).float().to(device, non_blocking=True)
		self.cell_feats = np.log1p(self.cell_feats)
		self.label_info = pickle.load(open(os.path.join(self.data_dir, "label_info.pickle"), "rb"))
		if "batch_id" in self.config or "library_id" in self.config:
			if "batch_id" in self.config:
				label = np.array(self.label_info[self.config["batch_id"]])
			else:
				label = np.array(self.label_info[self.config["library_id"]])
			uniques = np.unique(label)
			target2int = np.zeros((len(label), len(uniques)), dtype='float32')
			
			for i, t in enumerate(uniques):
				target2int[label == t, i] = 1
			print(target2int.shape)
			self.cell_feats = np.concatenate([self.cell_feats, target2int], axis=-1)
		self.cell_feats = np.concatenate([np.zeros((1, self.cell_feats.shape[-1])), self.cell_feats], axis=0).astype(
			'float32')
		
		embeddings_initial, attribute_dict, targets_initial = self.generate_attributes()
		
		sparse_chrom_list = np.load(os.path.join(self.temp_dir, "sparse_nondiag_adj_nbr_1.npy"), allow_pickle=True)
		filesize = os.path.getsize(os.path.join(self.temp_dir, "sparse_nondiag_adj_nbr_1.npy"))
		filesize_in_GB = filesize / (1024*1024*1024)
		if filesize_in_GB > 20:
			self.precompute_weighted_nbr = False
			global precompute_weighted_nbr
			precompute_weighted_nbr = self.precompute_weighted_nbr
		
		for i in range(len(sparse_chrom_list)):
			for j in range(len(sparse_chrom_list[i])):
				sparse_chrom_list[i][j] = sparse_chrom_list[i][j].astype('float32')
		
		if not mem_efficient_flag:
			sparse_chrom_list_GCN = sparse_chrom_list
			sparse_chrom_list_dict = copy.deepcopy(sparse_chrom_list)
			conv_weight = torch.ones((1, 1, 3, 3)).float()
			for chrom in range(len(sparse_chrom_list)):
				for cell in range(len(sparse_chrom_list[0])):
					sparse_chrom_list_dict[chrom][cell] = np.array(sparse_chrom_list_dict[chrom][cell].todense())
					m = sparse_chrom_list_dict[chrom][cell][None, None, :, :]
					m = torch.from_numpy(m).float()
					m = F.conv2d(m, conv_weight, padding=2)
					sparse_chrom_list_dict[chrom][cell] = m.detach().cpu().numpy()[0, 0, 1:-1, 1:-1]
		else:
			sparse_chrom_list_GCN = sparse_chrom_list
			sparse_chrom_list_dict = sparse_chrom_list
		
		if self.mode == 'classification':
			train_weight_mean = np.mean(train_weight)
			
			train_weight, test_weight = transform_weight_class(train_weight, train_weight_mean, neg_num), \
			                            transform_weight_class(test_weight, train_weight_mean, neg_num)
		elif self.mode == 'rank':
			train_weight = [x + 1 for x in train_weight]
			test_weight = [x + 1 for x in test_weight]
		
		
		# Constructing the model
		self.node_embedding_init = MultipleEmbedding(
			embeddings_initial,
			self.dimensions,
			False,
			num_list, targets_initial).to(device, non_blocking=True)
		
		self.node_embedding_init.wstack[0].fit(embeddings_initial[0], 300,
		                                       sparse=False,
		                                       targets=torch.from_numpy(targets_initial[0]
		                                                                ).float().to(device, non_blocking=True),
		                                       batch_size=1024)
		
		self.higashi_model = Hyper_SAGNN(
			n_head=8,
			d_model=self.dimensions,
			d_k=16,
			d_v=16,
			diag_mask=True,
			bottle_neck=self.dimensions,
			attribute_dict=attribute_dict,
			cell_feats=self.cell_feats,
			encoder_dynamic_nn=self.node_embedding_init,
			encoder_static_nn=self.node_embedding_init,
			chrom_num=len(self.chrom_list)).to(device, non_blocking=True)
		
		
		
		cell_neighbor_list = [[i] for i in range(self.num[0] + 1)]
		cell_neighbor_weight_list = [[1] for i in range(self.num[0] + 1)]
		
		# construct the dataloader
		self.training_data_generator = DataGenerator(train_data, train_chrom, train_weight,
		                                             int(self.batch_size / (neg_num + 1) * self.collect_num),
		                                             True, num_list, k=self.collect_num)
		self.validation_data_generator = DataGenerator(test_data, test_chrom, test_weight,
		                                               int(self.batch_size / (neg_num + 1)),
		                                               False, num_list, k=1)
```

Based on the code the neg_num is defined even before DataGenerator, I guess the reason that progressbar doesn't show in notebook mainly because ipywidget or sth like that (display )

**Comment by ruochiz** [comment]
I think I figured why the error pops though, based on what is described here: https://stackoverflow.com/questions/74210613/upgrading-python-version-to-3-9-on-macos-now-gives-variable-not-defined-error
where on macos, python changes the default multiprocessing method from fork to spawn. 

Could you try doing this
```
import multiprocessing
multiprocessing.set_start_method('fork')
```
before importing any packages to see if that fixes the error?
I do intend to remove some usage of global variables in the next release, but that can take a while.

**Comment by Queen0044** [comment]
Dear Ruochi,

Thank you for your help. It finally works on my end now!

I’m now trying to skip the data processing steps and directly run the imputation step in your paper on some simulated data and get the imputed data. My simulated dataset is in matrix format, with the (i,j) position being the number of contacts between loci i and j. Do you have any suggestions on how to make this happen?

Best;
Qing

From: ruochiz ***@***.***>
Reply-To: ma-compbio/Higashi ***@***.***>
Date: Thursday, March 23, 2023 at 12:04 AM
To: ma-compbio/Higashi ***@***.***>
Cc: Queen0044 ***@***.***>, Author ***@***.***>
Subject: Re: [ma-compbio/Higashi] NameError: name 'neg_num' is not defined (Issue #29)

I think I figured why the error pops though, based on what is described here: https: //stackoverflow. com/questions/74210613/upgrading-python-version-to-3-9-on-macos-now-gives-variable-not-defined-error where on macos, python changes the default


I think I figured why the error pops though, based on what is described here: https://stackoverflow.com/questions/74210613/upgrading-python-version-to-3-9-on-macos-now-gives-variable-not-defined-error<https://urldefense.com/v3/__https:/stackoverflow.com/questions/74210613/upgrading-python-version-to-3-9-on-macos-now-gives-variable-not-defined-error__;!!KGKeukY!zqb9chaqVXpooBeSOXNnSiAXfcaTJs8hFr_fKSWZyxu0PBC4u5PXOhuSNUbM59M98-oevCBBL23r-_j5P0B5q3ETNg$>
where on macos, python changes the default multiprocessing method from fork to spawn.

Could you try doing this

import multiprocessing

multiprocessing.set_start_method('fork')

before importing any packages to see if that fixes the error?
I do intend to remove some usage of global variables in the next release, but that can take a while.
