### ISSUE TITLE
About batch effect

### ISSUE THREAD

**Issue by sshen82** [ma-compbio/Higashi#3]
Hi, I have one question on the batch effect. In the pickle file, we can input the batch for the data, but when I look at the output of the data, the batch effect is not eliminated. I looked at the paper, and it doesn't talk about batch effect removal, and I just want to make sure if it is removed in your model.

**Comment by ruochiz** [comment]
Removing batch effect with our model is still an on-going effort. The uploaded version only uses the batch id in the visualization step to inspect if batch effect exists in the data. We are currently working on something to use batch id as input to regress out the batch effect during the training process. I will update the repo after systematic evaluation to see if such model design can effectively remove batch effect.
