### ISSUE TITLE
Some problem about color

### ISSUE THREAD

**Issue by yangfeizZZ** [ma-compbio/Higashi#31]
Hi
When i change the UMAP plot color, it not change. So i don't know why. In my label_info.pickle, it have cell information.
Thank you for your reply.

**Comment by ruochiz** [comment]
Hey,

Could you provide more info. Like, how you store cell info in label_info.pickle (how many options are there, like is it a categorical label or a continuous one, if it's categorical, how many categories.), where did you change the color, what's the expected behavior etc.

**Comment by yangfeizZZ** [comment]
Hello
Thank you. My label_info.pickle is like this:{'cell_type': ['CK','CK', 'CK', 'CK','EE','EE','EE','EE'],'batch':['batch1','batch2','batch3']}. I used bokeh to visualization.When i change the color scheme, there is no color change.

> Hey,
> 
> Could you provide more info. Like, how you store cell info in label_info.pickle (how many options are there, like is it a categorical label or a continuous one, if it's categorical, how many categories.), where did you change the color, what's the expected behavior etc.

**Comment by ruochiz** [comment]
I see. Um, couple things to check. 
1. Is the cell_type and 'batch' the same length of the cells
2. You can check the output or log of Higashi_vis on the server you run it on, and it should print sth when you change the color scheme.

**Comment by yangfeizZZ** [comment]
I know the problem. My cell_type length is same as the contacts length not rather than  cells length.

Thank you~~

**Comment by ruochiz** [comment]
Cool. Glad to help. Closing this issue now.
