### ISSUE TITLE
higashi.process_data() won't finish 

### ISSUE THREAD

**Issue by jshi7** [ma-compbio/Higashi#35]
Hello! I'm trying to process ~5000 cells using higashi. The fast higashi model works on my data, but I'd like to do downstream TAD/ other analysis, so I was trying to initialize the higashi model using higashi.process_data() but it won't finish even after a day of running. I used 128 GB of memory, 2 GPU, and 16 CPU, and it always gets stuck in the middle of create_matrix -- is there anything I could do to fix this?
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/29166540/236931416-b11af674-f7a4-40c9-b00a-302eb4d9ada9.png">

<img width="364" alt="image" src="https://github.com/ma-compbio/Higashi/assets/29166540/ab28e7ef-db37-4e04-990f-dfbd10212c30">

Thank you so much!

**Comment by ruochiz** [comment]
If you keyboardinterrupt the code, could you attach the final error report here so I can check which part it got stuck on? Thx

My guess is that it got stuck on generate_feats for cell nodes part, but would be good to have some confirmation.

**Comment by jshi7** [comment]
I unfortunately am running it as job on slurm.. so I'm not sure how I would do this (but will look into it). but node_feats.hdf5 is definitely not complete b/c I tried running the next step (prep_model) and it gave error because of that file

**Comment by jshi7** [comment]
<img width="1035" alt="image" src="https://github.com/ma-compbio/Higashi/assets/29166540/c5aeebc2-4d90-46e3-a430-ef6cac48642f">
Here is the error!

**Comment by ruochiz** [comment]
Is this the beginning of the error? Usually the actual error part from a multiprocessing job would be on the top. 
I'm guessing maybe it is caused by the multiprocessing setting which I can add a patch quickly, but would be good to confirm which part causes the error.

**Comment by jshi7** [comment]
<img width="1010" alt="image" src="https://github.com/ma-compbio/Higashi/assets/29166540/3d8e7555-03f2-45d6-b1e1-64092d4ca90e">
<img width="1009" alt="image" src="https://github.com/ma-compbio/Higashi/assets/29166540/1cbf8bd5-70ef-4541-88f8-a3e10014f38e">
Sorry about this; I attached the full error!

**Comment by ruochiz** [comment]
Hey I just commit a patch for this, could you check to see if that fixes the error. So, after you pull the repo, update the package, for `higashi_model.process_data()` could you do `higashi_model.process_data(disable_mpl=True)` instead, to disable multiprocessing for creating sparse matrices and see if that fixes the bug. Thanks

**Comment by jshi7** [comment]
Thank you for your help! unfortunately, I think it's still getting stuck even after I git pulled and set disable_mpl=True

**Comment by ruochiz** [comment]
Hum.. Can you kill it and attach the full error information. I think now it would show what the actual part it stuck on

**Comment by jshi7** [comment]
Actually I tried rerunning it and it worked this time!! thank you so much for your help!!

**Comment by ruochiz** [comment]
Oh... Cool. So it is the multiprocessing stuff.

**Comment by XiongGZ** [comment]
@ruochiz Hello! I try to use `higashi_model.process_data(disable_mpl=True)`  to solve the problem, 
but I got an error `TypeError: process_data() got an unexpected keyword argument 'disable_mpl'`
my higashi version is **higashi  0.1.1a1  py_0**
What can I do to solve this problem?

**Comment by XiongGZ** [comment]
> @ruochiz Hello! I try to use `higashi_model.process_data(disable_mpl=True)` to solve the problem, but I got an error `TypeError: process_data() got an unexpected keyword argument 'disable_mpl'` my higashi version is **higashi 0.1.1a1 py_0** What can I do to solve this problem?

I changed the default disable_mpl value in Process.py, but it didn't work
from `def create_matrix(config, disable_mpl=False)` to `def create_matrix(config, disable_mpl=True)`

**Comment by ruochiz** [comment]
Could you try to run it with just `higashi_model.process_data()` see if that fixes the issue? Thx!

**Comment by XiongGZ** [comment]
![image](https://github.com/ma-compbio/Higashi/assets/63765061/c84fda01-3432-4c71-912b-6897b5cbc022)
It didn't work, should I change the **default disable_mpl value in Process.py** back to `False`?
(different datasets have different results. In another dataset, it worked but very slowly)
![image](https://github.com/ma-compbio/Higashi/assets/63765061/5aca0a28-4bf6-4469-aae6-aa0d3be9d8a0)
I found the **Process.py** in **higashi 0.1.1a1 py_0** doesn't have the parameter **disable_mpl**, I download Process.py from GitHub to cover the local Process.py and then change the default value.

**Comment by ruochiz** [comment]
Right. The disable_mpl options would disabled multiprocessing, and only use one thread to run the program, hence it's expected to be slow. It's mainly used for debugging purpose (and not included in any release version). I added this option because error in child processes sometimes are not printed in the main program. 
Usually the error of multiprocessing stucks happens on windows machine. 

It's suggested that by default, one uses the program with mpl (so disable_mpl=False). Did you find the code stucked at the processing stage?

**Comment by XiongGZ** [comment]
> 

Yes, the code is stuck at the processing stage `higashi_model.process_data()`, I run the process_data() 50 minutes ago, but only finished 5%. (GPU number: 5)
![image](https://github.com/ma-compbio/Higashi/assets/63765061/0aec83fd-47ce-40ff-9b50-57f57b78b04c)

**Comment by ruochiz** [comment]
Hum. The process_data does not use gpu. The creating matric tasks can be slow depending on the parameters. What's the number of cells, resolution of the contact map, and did you end up using `disable_mpl` or not?

And, when the code is running, could you check htop or top to see if Higashi is using multiple cores efficiently or not? Thanks!

**Comment by XiongGZ** [comment]
I run the Higashi on the GPU node. There are about 7000 cells, and the resolution is 50k. The value of parameter `disable_mpl` was set **False** (I checked Higashi was using multiple cores). Maybe the resolution is too small?

**Comment by ruochiz** [comment]
These all sounds like reasonable parameters. 50k is a bit small, but Higashi should be able to handle that. 
It does seem like there are only 3,103,646 contacts for 7k cells, so on average each cell gets ~360 non-zero entries, which is really small. 
For comparisons, one of the sparser scHiC dataset, the 4DN sciHi-C dataset has ~103,497,337 for 16,707 cells, and are usually processed at 500kb or 1Mb resolution. 

Just for debugging purpose, I tested to process 4DN sciHi-C dataset at 50kb on a GPU node with about 32 CPU threads,  the running speed is roughly like this (the config name says 500k, but I changed it to 50kb as shown): 

![CleanShot 2023-08-22 at 22 37 11](https://github.com/ma-compbio/Higashi/assets/8788626/70e44fc5-ff4c-4fc2-b15b-bbc2f00de2f7)
![CleanShot 2023-08-22 at 22 58 55](https://github.com/ma-compbio/Higashi/assets/8788626/b083c3a3-36a0-49f1-ae32-6636a5e1377c)


For troubleshooting, if you are comfortable, you can share a fraction of the dataset that can replicate this behavior here: zhangruo@broadinstitute.org and I can help to take a look later.

**Comment by XiongGZ** [comment]
Relate data has been sent to you. Thanks for your patience!
