### ISSUE TITLE
error when running scTAD.py

### ISSUE THREAD

**Issue by jshi7** [ma-compbio/Higashi#37]
Hello, 
I get the following error when running scTAD.py with default (just` python Higashi/higashi/scTAD.py -c config.JSON`) 
<img width="1037" alt="image" src="https://github.com/ma-compbio/Higashi/assets/29166540/2d7ce4b8-9739-4956-9633-5a0a26757add">

However, if I run at `--window_ins 2000000 --window_tad 2000000` it seems to work. Could you let me know why this is the case? Do i need to increase the resolution from previous steps? I set my resolution in config file as follows: 
<img width="245" alt="image" src="https://github.com/ma-compbio/Higashi/assets/29166540/dd8bec94-8408-4a09-a50b-c57c49ca370d">

Thank you!!

**Comment by ruochiz** [comment]
The window_ins and window_tad needs to be at least 2x the resolution you use for training and imputation. 
And 1mb is probably too large for calling TADs
