### ISSUE TITLE
ERROE when run process.py: no config file

### ISSUE THREAD

**Issue by shinohara-xiao** [ma-compbio/Higashi#44]
Hi !
When I'm running Process.py `python Process.py` I got an error like this:
No such file or directory:  './config.JSON'
Do I need to construct the file on my own or do I miss some important steps that used to generate the JSON file ?
How can I get this JSON file ?

Thank you very much.

**Comment by ruochiz** [comment]
It's something you need to construct on your own, which contains all the information the program need such as file location, genome reference etc. See wiki page here: https://github.com/ma-compbio/Higashi/wiki/Configure-the-parameters

And also tutorials on the wiki page for examples of that
