### ISSUE TITLE
Predicting structures from embedding vector

### ISSUE THREAD

**Issue by donalday** [ma-compbio/Higashi#45]
Hi [ruochiz](https://github.com/ruochiz),

Thank you for your wonderful tool. I started using the original Higashi API (not Fast-Higashi).
I followed the Ramani et al.ipynb tutorial and it runs smoothly.
After training, I want to generate predicted contact matrix of new samples.
Is there a way to feed coordinates of embedding vector to the higashi_model object to generate the corresponding contact matrices (virtual 'raw', 'impute no nbr' and 'impute with nbr' matrices')?

Donald

**Comment by ruochiz** [comment]
Hi,

Thank you for your interest! Yes, I think it would be a good idea to generalize prediction to unseen single cells, and it's technically possible with Higashi. But the current implementation of it does not support that (and I don't have a plan to implement that recently).

A hacky way to do it would probably be first create some random contacts for the new samples as place holders, train the model. And then replace the contacts with actual ones... and just do the imputation. That being said, it's not tested, and I don't know if it'll function normally.

**Comment by donalday** [comment]
Thank you Ruochiz. That's very helpful.
