### ISSUE TITLE
 wrapper.fast_process_data() - method does not exist

### ISSUE THREAD

**Issue by GMFranceschini** [ma-compbio/Higashi#46]
Dear developers, I am trying to run your notebook tutorials and encountered this issue with Fast Higashi. I am on the Ramani notebook, but it seems to be a shared problem.
The method does not seem to exist (also checked with `help(wrapper)`). Could you please advise? 
I installed FastHigashi from conda as recommended, and also checked for updates.

In addition, I found other minor mistakes in the Ramani notebook, like ‘batch_id’ and not `batch`, and `higashi_model` instead of `higashi`. Hope this can help.

**Comment by GMFranceschini** [comment]
I solved the issue by reinstalling FastHigashi on a clean conda env. I thought Higashi and FastHigashi were compatible and could be installed in the same env, but that doesn't seem to be the case.

**Comment by ruochiz** [comment]
Sorry for the confusion.
