### ISSUE TITLE
how the cell_name in data.txt corresponds to the cell_type in label_info.pickle？

### ISSUE THREAD

**Issue by LHXqwq** [ma-compbio/Higashi#53]
Could you please explain how the cell_name in data.txt corresponds to the cell_type in label_info.pickle? I want to analyze my own data but am unsure how to construct the input data.

**Comment by ruochiz** [comment]
The cell_id column in the data.txt should be starting from 0, things like 0,1,2,3,4,5
And that should correspond to the order of cells, so the cell_type in the label_info.pickle should be organized accordingly.

**Comment by Accompany0313** [comment]
Is the cell_id in chr1_exp1_nbr_0_impute.hdf5 in the same order as the cells in the label_info file? I use filelist.txt for my data.

**Comment by ruochiz** [comment]
yes, if you use file list, it would be the id starting from 0, in the same order as the cells in file list.txt
