### ISSUE TITLE
How to set fast and memory saving mode?

### ISSUE THREAD

**Issue by GMFranceschini** [ma-compbio/Higashi#59]
In https://github.com/ma-compbio/Higashi/wiki/Runtime-of-Higashi and in the Higashi paper, two modes are reported. I would like to use the memory-saving one (I get OOM errors while running single chromosomes, both chr1 and chr6 at 100kb resolution on my GPU), how can I set this? 
I can't find this information in the wiki.
Thank you!

**Comment by ruochiz** [comment]
by default, mem_efficient_flag is always on now.
