### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by tarak77** [ma-compbio/Higashi#6]
Hey @ruochiz ,
So in the output embedding file `{embedding_name}_0_origin.npy `, the rows are the cells in the same ordering as the `cell_id` we give(say 0,1,2,....,#cell-1) to generate the `data.txt` file right??

**Comment by ruochiz** [comment]
Yes. You understanding is correct. BTW, my email is ruochiz@andrew.cmu.edu, if you prefer, I could answer questions or help debugging through email. 😄

**Comment by tarak77** [comment]
Sounds good! I follow you on twitter to haha
