### ISSUE TITLE
Clarification on the interpretation of inputed matrices

### ISSUE THREAD

**Issue by GMFranceschini** [ma-compbio/Higashi#60]
I was wondering if you could clarify to me what is the interpretation of values in imputed matrices with Higashi. I see that the value of the entries ranges from -1 to +1, shall I interpret them as the result of Pearson correlation? Is there any way to recover values that are compatible with a raw Hi-C matrix or a normalized one?
Thank you for any tip

**Comment by ruochiz** [comment]
Hum. The output should always be >0, if mode=='classification' it should be a value between 0 - 1 as a probability of observing a contacts, otherwise it should be a value >= 0 as a regression contacts. 

Could you provide screenshot / code of how you fetch the imputed matrices?

**Comment by GMFranceschini** [comment]
Apologies, I didn't look into my inputed matrices and I was asking based on the figure reported here: https://github.com/ma-compbio/Higashi/wiki/Output-of-Higashi-main and in Fig. 2 of the original paper. I saw that the color range in the heatmap goes from -1 to +1 and got confused.
I checked the imputed values and they are all non-negative, thank you
