### ISSUE TITLE
scTAD calling

### ISSUE THREAD

**Issue by tarak77** [ma-compbio/Higashi#7]
Hey @ruochiz ,
I am trying to call TADs and compartments on my imputed maps at 1mb resolution. 
In the `scTAD.py` code, I use `-n --window_ins 1000000 --window_tad 1000000`. 

Although the wiki says that 

> When including --neighbor or -n, the algorithm will call TADs on the imputed contact maps with neighboring cells' information utilized.

I get the error:

```
usage: scTAD.py [-h] [-c CONFIG] [-n NEIGHBOR] [--window_ins WINDOW_INS]
                [--window_tad WINDOW_TAD]
scTAD.py: error: argument -n/--neighbor: expected one argument
```

Also when I explicitly specify -n 5 the same as what I give "neighbor_num":5 in json file....I get the following error:

`unable to open *_nbr_1_impute.hdf5`

Any help will be great!!

Your TAD/compartments result figures are really useful and awesome!! Is there a tutorial available to create figures like those?

**Comment by ruochiz** [comment]
For future reader of this issue: the bug has been fixed. The -n without inputing number should be the correct way of using the script.
